//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.TraLoiBinhLuans = new HashSet<TraLoiBinhLuan>();
        }
    
        public int MaBL { get; set; }
        public string NoiDungBL { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> MaCTDDH { get; set; }
    
        public virtual ChiTietDonDatHang ChiTietDonDatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraLoiBinhLuan> TraLoiBinhLuans { get; set; }
    }
}
