//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ID { get; set; }
        public Nullable<int> MaShop { get; set; }
        public Nullable<int> MaThanhVien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<bool> Client { get; set; }
        public string Text { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
