//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Id { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual ThanhVien ThanhVien1 { get; set; }
    }
}
