//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietFlashSale
    {
        public int MaChiTietSale { get; set; }
        public Nullable<int> MaSale { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaShop { get; set; }
        public Nullable<bool> NgungSale { get; set; }
    
        public virtual FlashSale FlashSale { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
