//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMatHangKinhDoanh
    {
        public int MaCTMatHang { get; set; }
        public Nullable<int> MaMatHang { get; set; }
        public string TenLSP { get; set; }
        public Nullable<int> MaLSP { get; set; }
    
        public virtual loaiSanPham loaiSanPham { get; set; }
        public virtual MatHangKinhDoanh MatHangKinhDoanh { get; set; }
    }
}
