//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
        }
    
        public int MaDDH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> UuDai { get; set; }
        public Nullable<int> MaTinhTrangGiaoHang { get; set; }
        public string HinhThucThanhToan { get; set; }
        public Nullable<int> MaHuyen { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public Nullable<int> MaXa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual Huyen Huyen { get; set; }
        public virtual Tinh Tinh { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual Xa Xa { get; set; }
        public virtual DonDatHang DonDatHang1 { get; set; }
        public virtual DonDatHang DonDatHang2 { get; set; }
        public virtual TinhTrangGiaoHang TinhTrangGiaoHang { get; set; }
    }
}
