//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangThanhVien
    {
        public int ID { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> ToiThieu { get; set; }
        public Nullable<int> ToiDa { get; set; }
    }
}
