//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public int ID { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SL { get; set; }
        public string CodePhieuNhap { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
