//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ChatwithShop = new HashSet<ChatwithShop>();
            this.ChiTietFlashSale = new HashSet<ChiTietFlashSale>();
            this.DonDatHang = new HashSet<DonDatHang>();
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int MaShop { get; set; }
        public string TenShop { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string HinhAnh { get; set; }
        public string TaiKhoan { get; set; }
        public string Pass { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public Nullable<int> MaHuyen { get; set; }
        public Nullable<int> MaXa { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<int> captcha { get; set; }
        public Nullable<int> MaMatHang { get; set; }
        public string ChuSoHuu { get; set; }
        public Nullable<bool> DaKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatwithShop> ChatwithShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietFlashSale> ChiTietFlashSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHang { get; set; }
        public virtual Huyen Huyen { get; set; }
        public virtual MatHangKinhDoanh MatHangKinhDoanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
        public virtual Tinh Tinh { get; set; }
        public virtual Xa Xa { get; set; }
    }
}
