//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBaoDH
    {
        public int ID { get; set; }
        public string MaDH { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<int> MaTV { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
